from google import genai
from google.genai import types

from backend.optimizer import (
    optimize_network,
    run_threshold_sweep,
)


client = genai.Client()

# Stores the latest result generated by one of Gemini's tools.
# Fine for our local single-user demo.
latest_tool_result = None


def optimize_network_tool(
    data_rate_threshold: float,
    path_loss_exponent: float,
):
    """
    Optimize one CAV V2I network scenario.

    Args:
        data_rate_threshold:
            Required data rate in bits per second.

        path_loss_exponent:
            Wireless path loss exponent.

    Returns:
        Optimization results including BS density,
        achievable rate, optimal speed, and traffic flow.
    """

    global latest_tool_result

    result = optimize_network(
        data_rate_threshold=data_rate_threshold,
        path_loss_exponent=path_loss_exponent,
    )

    latest_tool_result = {
        "tool": "optimize_network",
        "data": result,
    }

    return result


def compare_network_scenarios(
    data_rate_threshold_1: float,
    path_loss_exponent_1: float,
    data_rate_threshold_2: float,
    path_loss_exponent_2: float,
):
    """
    Compare two CAV V2I network scenarios.

    Args:
        data_rate_threshold_1:
            Required data rate for scenario 1 in bits per second.

        path_loss_exponent_1:
            Path loss exponent for scenario 1.

        data_rate_threshold_2:
            Required data rate for scenario 2 in bits per second.

        path_loss_exponent_2:
            Path loss exponent for scenario 2.

    Returns:
        Optimization results for both scenarios.
    """

    global latest_tool_result

    scenario_1 = optimize_network(
        data_rate_threshold=data_rate_threshold_1,
        path_loss_exponent=path_loss_exponent_1,
    )

    scenario_2 = optimize_network(
        data_rate_threshold=data_rate_threshold_2,
        path_loss_exponent=path_loss_exponent_2,
    )

    result = {
        "scenario_1": scenario_1,
        "scenario_2": scenario_2,
    }

    latest_tool_result = {
        "tool": "compare_network_scenarios",
        "data": result,
    }

    return result


def analyze_threshold_range(
    start_threshold: float,
    end_threshold: float,
    path_loss_exponent: float,
    num_points: int = 20,
):
    """
    Analyze network performance across a range of
    data-rate thresholds.

    Args:
        start_threshold:
            Starting threshold in bits per second.

        end_threshold:
            Ending threshold in bits per second.

        path_loss_exponent:
            Wireless path loss exponent.

        num_points:
            Number of points to calculate across the range.

    Returns:
        Optimization results for every threshold.
    """

    global latest_tool_result

    results = run_threshold_sweep(
        start_threshold=start_threshold,
        end_threshold=end_threshold,
        num_points=num_points,
        path_loss_exponent=path_loss_exponent,
    )

    latest_tool_result = {
        "tool": "analyze_threshold_range",
        "data": results,
    }

    return results


def ask_agent(question: str):
    global latest_tool_result

    # Reset before every question
    latest_tool_result = None

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=question,
        config=types.GenerateContentConfig(
            tools=[
                optimize_network_tool,
                compare_network_scenarios,
                analyze_threshold_range,
            ],
            system_instruction="""
You are a network optimization assistant for a
Connected and Autonomous Vehicle (CAV) V2I network.

Use the provided tools for all numerical network calculations.
Never estimate or invent optimization results.

IMPORTANT TOOL SELECTION RULES:

When the user asks about ONE network scenario,
use optimize_network_tool.

When the user explicitly asks to compare TWO individual scenarios,
use compare_network_scenarios.

When the user asks how something changes FROM one threshold TO another,
or asks for a range, trend, curve, sweep, graph, or plot,
you MUST use analyze_threshold_range.

For range analysis, use enough points to show the trend,
normally 20 points unless the user specifies otherwise.

Use m/s for speed.
Use Mbps or Gbps for data rates.
Use BS/m for base station density.
Traffic flow Q is measured in vehicles per second.

Mention when the maximum BS density constraint is reached.

Respond in plain text.
Do not use LaTeX or mathematical markup.
"""
        ),
    )

    return {
        "answer": response.text,
        "tool_result": latest_tool_result,
    }


if __name__ == "__main__":
    while True:
        question = input("\nAsk the network agent: ")

        if question.lower() in ["exit", "quit"]:
            break

        result = ask_agent(question)

        print("\nAgent:")
        print(result["answer"])

        print("\nTool result:")
        print(result["tool_result"])